### ISSUE TITLE
We would like the language to be lemmatized

### ISSUE THREAD

**Issue by ellismiranda** [jambran/elite_speak#34]
- this may not be required if Keigh/Marc's corpus handles non-lemmatized

**Comment by ellismiranda** [comment]
in investigating this I've come up with a few things:
- do we want to lemmatize every word? or stem most of them and lemmatize the others
- how does lemmatizing words fit in with our ideas of similar words - "Get Elite" ?

**Comment by ellismiranda** [comment]
- ability to lemmatize is added in, although it doesn't do much for many words. currently using the standard nltk one.

**Comment by arcturusn7** [comment]
I'm getting an error for some words with lemmatizer?

![error2](https://user-images.githubusercontent.com/11062474/34130416-b89e672c-e415-11e7-995e-975bafc01005.jpg)

**Comment by ellismiranda** [comment]
weird I just tried syzygy and it didn't have an issue

**Comment by ellismiranda** [comment]
@arcturusn7 found the issue. gonna make a fix now.
https://stackoverflow.com/questions/27433370/what-would-cause-wordnetcorpusreader-to-have-no-attribute-lazycorpusloader

**Comment by arcturusn7** [comment]
Awesome
